@base=http://localhost:{{PORT}}
###
POST {{base}}/api/auth/login
Content-Type: application/json

{
    "uname": "Erik",
    "psw": "123"
}
###
POST {{base}}/api/auth/register
Content-Type: application/json

{
    "uname": "Erik",
    "email": "erik@gmail.com",
    "mobnr": "07343827",
    "psw": "1234567890",
    "repsw": "1234567890",
    "avatar": "a.jpg"
}
