@base=http://localhost:{{ PORT }}/api
###
POST {{ base }}/auth/login
Content-Type: application/json
apiKey: {{ APIKEY }}

{
    "uname": "erik",
    "psw": "1234567890"
}
###
POST {{ base }}/auth/register
Content-Type: application/json
apiKey: {{ APIKEY }}

{
    "uname": "Erik",
    "email": "erik@gmail.com",
    "mobnr": "07343827",
    "psw": "1234567890",
    "repsw": "1234567890",
    "avatar": "a.jpg"
}


GET {{ base }}/users/
Content-Type: application/json
apiKey: {{ APIKEY }}

GET {{ base }}/users/1
Content-Type: application/json
apiKey: {{ APIKEY }}
